from .auth_routes import router as auth_router
from .user_routes import router as user_router
from .journey_routes import router as journey_router
from .upload_routes import router as upload_router
from .dashboard_routes import router as dashboard_router
from .analytics_routes import router as analytics_router
from .admin_routes import router as admin_router
from .quality_criteria_routes import router as quality_criteria_router
from .quality_tab_routes import router as quality_tab_router
from .webhook_routes import router as webhook_router
