from .auth_routes import router as auth_router
from .user_routes import router as user_router
from .journey_routes import router as journey_router
from .upload_routes import router as upload_router
from .dashboard_routes import router as dashboard_router
from .analytics_routes import router as analytics_router
from .admin_routes import router as admin_router
from .quality_criteria_routes import router as quality_criteria_router
from .quality_tab_routes import router as quality_tab_router
from .webhook_routes import router as webhook_router
from .system_routes import router as system_router
from .lumi_routes import router as lumi_router
from .admin_module_routes import router as admin_module_router
from .kosmo_routes import router as kosmo_router
from .driver_routes import router as driver_router
from .manual_routes import router as manual_router
from .ai_eval_routes import router as ai_eval_router
from .architecture_routes import router as architecture_router
